### PR TITLE
Implementing BrowserSync

### PR DESCRIPTION
**Pull request by MickCoelho**
Implementing BrowserSync using BrowserSync Webpack plugin

### CODE REVIEW

**Comment by antwan1986** [comment]
Fixes #98.

**Comment by antwan1986** [comment]
@MickCoelho - I think we may need to marry up some functionality here. I see in the documentation you've removed the `server` task but not the actual server code or NPM packages.

After thinking about it more, I wonder if our watch command should always be starting a server? Quite a lot of our Heroku builds have a dedicated server task which is what we tell Heroku to run to actually host and see the site.

Do we need some way to be able to run the server manually as well as having our watch task for CSS and JS plug into it? Whenever I get off of Miyagi I'll have a bit more of a look into this.

**Comment by MickCoelho** [comment]
@antwan1986 Indeed, I removed it from the doc as it shouldn't be used if you run `make watch` since the dev server from BrowserSync will start automatically. 
Relative to Heroku, doesn't it only run `npm start` by default? If so, that wouldn't be a problem since the BrowserSync server is only started when running `make watch` or `gulp watch`. 

Otherwise, it's absolutely no problem if we want it outside of the `make watch` command.

**Comment by antwan1986** [comment]
@MickCoelho - I've updated this PR a little bit. Just for your reference here's what I've done:

1) BrowserSync wasn't working for me because there was no `file` array in the plugin settings denoting which files need watching.
2) I moved the plugin into the `scripts` task like other Webpack plugins are located, but kept the Browser-sync settings in the `config.js` file.
3) I added a CLI override so that when you're watching via `gulp watch` you can turn off the Browser-sync server (for projects that are hosted on say, AppEngine, and have no need for Browser-sync).

**Comment by antwan1986** [comment]
@njmcode: Cliff notes below:

* Replaces `gulp-webserver` as a viable serving solution for prototypes and small projects.
* Brings browser-sync functionality such as live reloading of CSS, JS and image assets.
* Has been plumbed in so the server starts as soon as you start watching files (though this can be overridden).

**Pull request merged**
